# $NetBSD$
#

DISTNAME=	ncview-2.1.2
CATEGORIES=	science graphics
MASTER_SITES=	ftp://cirrus.ucsd.edu/pub/ncview/

MAINTAINER=	bacon4000@gmail.com
HOMEPAGE=	ftp://cirrus.ucsd.edu/pub/ncview/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

GNU_CONFIGURE=	yes

.include "../../uwm-pkgsrc-wip/netcdf-ftn/buildlink3.mk"
# .include "../../x11/libX11/buildlink3.mk"
.include "../../x11/libXaw/buildlink3.mk"
.include "../../graphics/png/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
