# $NetBSD$
#

DISTNAME=	cvs-1.11.23
CATEGORIES=	devel
MASTER_SITES=	http://ftp.gnu.org/non-gnu/cvs/source/stable/1.11.23/
EXTRACT_SUFX=	.tar.bz2

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	http://ftp.gnu.org/non-gnu/cvs/source/stable/1.11.23/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c c++

.include "../../mk/bsd.pkg.mk"
