#!/bin/sh -e

: ${PKGSRCDIR:=/usr/pkgsrc}

if [ $0 != ./audit ]; then
    printf "Must be run as ./audit.\n"
    exit 1
fi

for dir in *; do
    clear
    if [ -e $dir/Makefile ]; then
	categories=`ls $PKGSRCDIR/*/Makefile | awk -F / '{ print $4 }'`
	committed=0
	for category in $categories; do
	    if [ $category != uwm-pkgsrc-wip ] && [ -e $PKGSRCDIR/$category/$dir ]; then
		committed=1
		printf "Found $category/$dir\n\n"
		egrep '^PKGNAME=|^DISTNAME=' \
		    $PKGSRCDIR/uwm-pkgsrc-wip/$dir/Makefile \
		    $PKGSRCDIR/$category/$dir/Makefile
		read -p "Diff? y/[n] " diff
		if [ 0$diff = 0y ]; then
		    diff -ruN \
			$PKGSRCDIR/$category/$dir \
			$PKGSRCDIR/uwm-pkgsrc-wip/$dir | more
		    printf "\nDependent packages:\n"
		    fgrep uwm-pkgsrc-wip/$dir */Makefile || true
		    read -p "Remove? y/[n] " remove
		    if [ 0$remove = 0y ]; then
			svn rm $dir
			svn ci -m "${dir}: Remove obsolete package"
		    fi
		fi
	    fi
	done
	if [ $committed = 0 ]; then
	    printf "No other version of $dir.\n\n"
	    more $dir/DESCR $dir/Makefile
	    
	    chosen=0
	    while [ $chosen = 0 ]; do
		cat << EOM

1.. Remove
2.. Move to wip
3.. Ignore

EOM
		read -p "Your choice? " choice
		case 0$choice in
		01)
		    read -p "Are you sure? yes/[no] " sure
		    if [ 0$sure = 0yes ]; then
			svn rm $dir
			svn ci -m "${dir}: Remove obsolete package"
		    fi
		    chosen=1
		    ;;
		
		02)
		    chosen=1
		    ;;
		
		03)
		    chosen=1
		    ;;
		
		*)
		    printf "Invalid choice.\n"
		    ;;
		esac
		    
	    done
	fi
    fi
done

