#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-09-17  Jason Wayne BaconBegin
##########################################################################

usage()
{
    printf "Usage: $0 package\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

pkg=$1
deps="`grep -l uwm-pkgsrc-wip/$pkg */*`" || true
for file in $deps; do
    printf "Replacing uwm-pkgsrc-wip/$pkg with wip/$pkg in $file...\n"
    sed -e 's|uwm-pkgsrc-wip/$pkg|wip/$pkg|g' $file > $file.edit-deps
    mv -f $file.edit-deps $file
done
