#!/bin/sh -e

##########################################################################
#   Script description:
#       
#   Arguments:
#       
#   Returns:
#       
#   History:
#   Date        Name        Modification
#   2016-09-17  Jason Wayne BaconBegin
##########################################################################

usage()
{
    printf "Usage: $0 package\n"
    exit 1
}


##########################################################################
#   Main
##########################################################################

if [ $# != 1 ]; then
    usage
fi

pkg=$1
uwm=uwm-pkgsrc-wip/$pkg
wip=wip/$pkg
deps="`fgrep -s -l $uwm */*`" || true
for file in $deps; do
    printf "Replacing $uwm with $wip in $file...\n"
    sed -e "s|$uwm|$wip|g" $file > $file.edit-deps
    mv -f $file.edit-deps $file
done
