# $NetBSD$

DISTNAME=	pomgl-1.0
CATEGORIES=	jb-wip
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon4000@gmail.com
HOMEPAGE=	http://acadix.biz/Ports/distfiles/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

.include "../../jb-wip/glerl-lib/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
