#!/bin/sh -e

cd ${WRKDIR}
rm -f decrypt*
cp ${DISTDIR}/decrypt.c.gz .
gunzip decrypt.c.gz
cc -o decrypt decrypt.c
printf "Decrypt password: "
read password
# decrypt returns non-zero status even when it succeeds, so mask it with
# an if to prevent make from terminating
if printf "$password\n${DISTDIR}/dl_poly_4.03.tar.gE\n" | decrypt; then
fi
tar zxf ${DISTDIR}/dl_poly_4.03.tar.gz

