# $NetBSD$

BUILDLINK_TREE+=	py27-avro

.if !defined(PY27_AVRO_BUILDLINK3_MK)
PY27_AVRO_BUILDLINK3_MK:=

BUILDLINK_API_DEPENDS.py27-avro+=	py27-avro>=1.7.4
BUILDLINK_PKGSRCDIR.py27-avro?=	../../uwm-pkgsrc-wip/py-avro
.endif	# PY27_AVRO_BUILDLINK3_MK

BUILDLINK_TREE+=	-py27-avro
