# $NetBSD$

DISTNAME=	glerl-lib-1.0
CATEGORIES=	science
MASTER_SITES=	http://acadix.biz/Ports/distfiles/

MAINTAINER=	bacon@NetBSD.org
HOMEPAGE=	http://acadix.biz/Ports/distfiles/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
