# $NetBSD$

DISTNAME=	OpenBUGS-${PORTVERSION}
CATEGORIES=	uwm-pkgsrc-wip
MASTER_SITES=	 http://www.openbugs.net/w/OpenBUGS_3_2_3?action=AttachFile&do=get&target=

PORTVERSION=	3.2.3

HAS_CONFIGURE=		yes

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	http://www.openbugs.net/w/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

DEPENDS+=	glibc>0.0:../../wip/glibc/

# url2pkg-marker (please do not remove this line.)
.include "../../mk/bsd.pkg.mk"
