# $NetBSD$
#

DISTNAME=	dl_poly_3.10
CATEGORIES=	jb-wip
MASTER_SITES=	ftp://ftp.dl.ac.uk/ccp5/DL_POLY/TRANSFERS/
EXTRACT_SUFX=	.tar.gz

MAINTAINER=	INSERT_YOUR_MAIL_ADDRESS_HERE
HOMEPAGE=	ftp://ftp.dl.ac.uk/ccp5/DL_POLY/TRANSFERS/
COMMENT=	TODO: Short description of the package
#LICENSE=	# TODO: (see mk/license.mk)

PKG_DESTDIR_SUPPORT=	user-destdir

#WRKSRC=		${WRKDIR}/dl_poly_3.10.tar.gE
USE_LANGUAGES=	fortran

.include "../../mk/bsd.pkg.mk"
