#!/bin/sh -e

pkg_add libsndfile ncurses pcre readline zlib hicolor-icon-theme \
    arpack blas fftw fftwf lapack curl qt5-qtbase qt5-qttools \
    gperf fltk-1.3.3nb3 desktop-file-utils

if [ `uname` != "Darwin" ]; then
    pkg_add libX11
fi
