#!/bin/sh -e

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkg_delete='pkg_delete -f'
    $pkg_delete tabixpp smithwaterman fastahack filevercmp fsom multichoose \
	intervaltree vcflib vcftools rainbow bamtools freebayes stacks \
	Trimmomatic seqtk bedtools2 pear-merger samtools parallel ddocent || true
fi

prefix=$(dirname $(dirname $(which bmake)) | sed -e 's|pkg|pkgsrc|g')
echo $prefix
cd $prefix/uwm-pkgsrc-wip/ddocent
bmake clean
bmake clean-depends
bmake
# Do this late to minimize uninstalled time
bmake deinstall
bmake install

