#!/bin/sh -e

printf "Remove everything? y/[n] "
read remove
if [ 0$remove = 0y ]; then
    pkgin remove -y tabixpp smithwaterman fastahack filevercmp fsom multichoose \
	intervaltree vcflib vcftools rainbow bamtools freebayes stacks \
	Trimmomatic seqtk bedtools2 pear-merger samtools parallel ddocent || true
fi

pkgin install -y coreutils glib gnuplot parallel automake
pkgsrc=`auto-pkgsrc-dir`
cd $pkgsrc/wip/ddocent
bmake clean
#bmake clean-depends
bmake
# Do this late to minimize uninstalled time
bmake deinstall
bmake install

