#!/bin/sh -e

if which bmake; then
    make=bmake
else
    make=make
fi
pkgin install pkglint pkgdiff createbuildlink
cd $(auto-pkgsrc-dir)/uwm-pkgsrc-wip/pkg-dev
$make clean
$make clean-depends
$make distclean
$make deinstall
$make install
