#!/bin/sh -e

prefix=$(dirname $(dirname $(which bmake)) | sed -e 's|pkg|pkgsrc|g')
cd $prefix/uwm-pkgsrc-wip
svn up

# Allow auto-admin deinstall
pkgin remove -y auto-admin cluster-admin || true

cd $prefix/uwm-pkgsrc-wip/auto-admin
bmake distclean && bmake deinstall && bmake install

cd $prefix/uwm-pkgsrc-wip/cluster-admin-devel
bmake distclean && bmake deinstall && bmake install

cd ..
yes | ./clean-all

cluster-run -c "cd $prefix/uwm-pkgsrc-wip && svn up && (pkgin remove -y auto-admin cluster-admin || true) && rm -rf */work && cd cluster-admin-devel && rm -f $prefix/distfiles/auto-admin* && rm -f $prefix/distfiles/cluster-admin* && bmake deinstall && bmake install" all
