#!/bin/sh -e

prefix=$(dirname $(dirname $(which bmake)) | sed -e 's|pkg|pkgsrc|g')
cd $prefix/uwm-pkgsrc-wip
svn up

# Allow auto-admin deinstall
pkgin remove -y auto-admin cluster-admin || true

cd $prefix/uwm-pkgsrc-wip/auto-admin
bmake distclean && bmake deinstall && bmake install

cd $prefix/uwm-pkgsrc-wip/cluster-admin-devel
bmake distclean && bmake deinstall && bmake install

cd ..
yes | ./clean-all

cluster-run "cd $prefix/uwm-pkgsrc-wip && svn --non-interactive --trust-server-cert-failures=unknown-ca up" all
cluster-run -c 'pkgin remove -y cluster-admin' all || true
cluster-run "cd $prefix/uwm-pkgsrc-wip/auto-admin && bmake distclean && bmake deinstall && bmake install" all
cluster-run "cd $prefix/uwm-pkgsrc-wip/cluster-admin-devel && bmake distclean && bmake deinstall && bmake install" all

